export const mockAthletes = [
  {
    id: "1",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Diego",
    firstname: "Diego",
    lastname: "Figueiredo",
    nickname: "Quebra Queixo",
    birthdate: "1986-08-20T00:00:00Z",
    city: "Cascata",
    state: "Rio Grande do Sul",
    country: "Brasil",
    phone: "51997703846",
    document: "37736302627",
    email: "diego.figueiredo@email.com",
    weight: 90,
    height: 173,
    modalities: ["jiujitsu", "mma"],
    expertises: ["amateur", "semipro"],
    wins: 23,
    losses: 12
  },
  {
    id: "2",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos",
    firstname: "Carlos",
    lastname: "Silva",
    nickname: "Martelo",
    birthdate: "1992-03-15T00:00:00Z",
    city: "São Paulo",
    state: "São Paulo",
    country: "Brasil",
    phone: "11987654321",
    document: "12345678901",
    email: "carlos.silva@email.com",
    weight: 77,
    height: 175,
    modalities: ["muaythai", "boxing"],
    expertises: ["pro"],
    wins: 18,
    losses: 5
  },
  {
    id: "3",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ana",
    firstname: "Ana",
    lastname: "Santos",
    nickname: "Furacão",
    birthdate: "1995-11-08T00:00:00Z",
    city: "Rio de Janeiro",
    state: "Rio de Janeiro",
    country: "Brasil",
    phone: "21976543210",
    document: "98765432109",
    email: "ana.santos@email.com",
    weight: 61,
    height: 165,
    modalities: ["jiujitsu"],
    expertises: ["semipro"],
    wins: 15,
    losses: 3
  },
  {
    id: "4",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rafael",
    firstname: "Rafael",
    lastname: "Costa",
    nickname: "Demolidor",
    birthdate: "1988-07-22T00:00:00Z",
    city: "Belo Horizonte",
    state: "Minas Gerais",
    country: "Brasil",
    phone: "31965432109",
    document: "45678912345",
    email: "rafael.costa@email.com",
    weight: 84,
    height: 180,
    modalities: ["mma", "boxing"],
    expertises: ["pro"],
    wins: 31,
    losses: 8
  },
  {
    id: "5",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Juliana",
    firstname: "Juliana",
    lastname: "Oliveira",
    nickname: "Relâmpago",
    birthdate: "1993-12-03T00:00:00Z",
    city: "Curitiba",
    state: "Paraná",
    country: "Brasil",
    phone: "41954321098",
    document: "78912345678",
    email: "juliana.oliveira@email.com",
    weight: 57,
    height: 160,
    modalities: ["muaythai"],
    expertises: ["amateur"],
    wins: 12,
    losses: 7
  },
  {
    id: "6",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Bruno",
    firstname: "Bruno",
    lastname: "Ferreira",
    nickname: "Titã",
    birthdate: "1985-05-17T00:00:00Z",
    city: "Salvador",
    state: "Bahia",
    country: "Brasil",
    phone: "71943210987",
    document: "32165498732",
    email: "bruno.ferreira@email.com",
    weight: 93,
    height: 185,
    modalities: ["jiujitsu", "mma"],
    expertises: ["pro"],
    wins: 28,
    losses: 6
  },
  {
    id: "7",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mariana",
    firstname: "Mariana",
    lastname: "Lima",
    nickname: "Pantera",
    birthdate: "1990-09-25T00:00:00Z",
    city: "Fortaleza",
    state: "Ceará",
    country: "Brasil",
    phone: "85932109876",
    document: "65432198765",
    email: "mariana.lima@email.com",
    weight: 66,
    height: 168,
    modalities: ["boxing"],
    expertises: ["semipro"],
    wins: 20,
    losses: 4
  },
  {
    id: "8",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lucas",
    firstname: "Lucas",
    lastname: "Pereira",
    nickname: "Trovão",
    birthdate: "1994-01-12T00:00:00Z",
    city: "Recife",
    state: "Pernambuco",
    country: "Brasil",
    phone: "81921098765",
    document: "98732165432",
    email: "lucas.pereira@email.com",
    weight: 70,
    height: 172,
    modalities: ["muaythai", "jiujitsu"],
    expertises: ["amateur"],
    wins: 9,
    losses: 11
  }
]